// Copyright 2019-2025 @polkassembly/fellowship authors & contributors
// This software may be modified and distributed under the terms
// of the Apache-2.0 license. See the LICENSE file for details.

export const API_ERROR_CODE = {
	API_FETCH_ERROR: 'API_FETCH_ERROR',
	INVALID_PARAMS_ERROR: 'INVALID_PARAMS_ERROR',
	INVALID_SEARCH_PARAMS_ERROR: 'INVALID_SEARCH_PARAMS_ERROR',
	SUBSQUID_FETCH_ERROR: 'SUBSQUID_FETCH_ERROR',
	GITHUB_FETCH_ERROR: 'GITHUB_FETCH_ERROR',
	REQ_BODY_ERROR: 'REQ_BODY_ERROR',
	CLIENT_ERROR: 'CLIENT_ERROR',
	POST_NOT_FOUND_ERROR: 'POST_NOT_FOUND_ERROR',
	REACTION_ACTION_ERROR: 'REACTION_ACTION_ERROR',
	ADDRESS_NOT_FOUND_ERROR: 'ADDRESS_NOT_FOUND_ERROR',
	USER_NOT_FOUND_ERROR: 'USER_NOT_FOUND_ERROR',
	INVALID_NETWORK_ERROR: 'INVALID_NETWORK_ERROR'
};
